### ISSUE TITLE
Sandbox: Flag enum content is not displayed in 'View' mode

### ISSUE THREAD

**Issue by daalcant** [microsoft/OAT#67]
**Description:**
In the Sandbox, objects containing flag enum members do not display corresponding enum content when viewed. Only the label is displayed.
E.g. see FirewallObject flag enum member 'Profiles' 

**Expected behavior:**
Objects in 'View' mode should display all possible enum flag values as checkboxes, defaulting to unchecked.

**To Reproduce:**
1. Run ASA, open GUI
2. Click Sandbox page
3. Select type that contains flag enum input, e.g. FirewallObject
4. Create the object
5. Click 'View' tab to view the object, expand its contents
6. See labels where flag enum inputs are not being populated, for example 'Profiles' label when viewing FirewallObject

**Configuration:**
 - ASA Application Version: v2.3.146-beta
 - OAT Application Version: 718b12bddf671984074aefe98e6789c4dd0c7b95

**Comment by gfs** [comment]
> Modified FlagsInput.razor to still create checkboxes in cases where the flag enum member is null

This is probably the wrong approach.  This should be covered by the `set to null` checkbox already.

**Comment by gfs** [comment]
According to official documentation the way to check if a type is nullable is

`Nullable.GetUnderlyingType(type) != null`

https://docs.microsoft.com/en-us/dotnet/api/system.nullable.getunderlyingtype?view=net-5.0

However, this does not appear to work for Flag Enums, and this method will instead return `null`.  I've verified this behavior directly in OAT so it is not an ASA issue.  Unfortunately, it doesn't seem viable to de-nullable the Flag Enums in Attack Surface Analyzer as null is a valid value for them (some of the enums are only valid on windows systems and the flags are passed through.)

**Comment by gfs** [comment]
I've narrowed this problem down to only Enums that start as null.  Enums that are nullable but don't start as null now work.
